#pragma once
// Declarative config schema (8.7): every known key with its section, type and whether it
// is required. config.cpp validates the parsed TOML against this table and reports
// errors with line numbers; unknown keys are warnings so configs stay forward compatible.
// Sections "sim" and "backtest" are free-form (owned by the sim/backtest libraries).
//
// The doc strings are the key tables of docs/reference/configuration.md
// (python3 tools/docs_config_ref.py regenerates them): say what the key does, its unit and its
// default.
#include <cstddef>
#include <span>
#include <string_view>

namespace fastmm {

enum class KeyType : unsigned char { String, Int, Float, Bool, IntArray, StringArray, Table, Any };

struct KeySpec {
  std::string_view section;  // "engine", "venues.*", "instruments[]", "strategy", ...
  std::string_view key;
  KeyType type;
  bool required;
  std::string_view doc;
  // Connector-specific key: validated and documented here, but still handed to the connector
  // through VenueSection::extra (the generic parser does not interpret it).
  bool passthrough = false;
};

inline constexpr KeySpec kConfigSchema[] = {
    // [engine]
    {"engine",
     "name",
     KeyType::String,
     false,
     "session name, used in logs, journal file names and the status file (default \"fastmm\")"},
    {"engine",
     "cpu",
     KeyType::Int,
     false,
     "CPU core of the engine thread; -1 = not pinned (default -1)"},
    {"engine",
     "net_cpus",
     KeyType::IntArray,
     false,
     "CPU cores of the network threads, one per venue in order (default [])"},
    {"engine",
     "spin_mode",
     KeyType::String,
     false,
     "busy (spin forever) | adaptive (back off to short sleeps when idle; use on WSL2 and laptops) "
     "(default adaptive)"},
    {"engine",
     "net_backend",
     KeyType::String,
     false,
     "event loop of fastmm-live and fastmm-sim-exchange: epoll | io_uring (Linux 5.13 or newer; "
     "falls back to epoll with a warning) (default epoll)"},
    {"engine",
     "journal",
     KeyType::Bool,
     false,
     "record every consumed event to a .fmj journal (default true)"},
    {"engine", "journal_dir", KeyType::String, false, "directory for journals (default \"runs\")"},
    {"engine",
     "epoch_file",
     KeyType::String,
     false,
     "session epoch file, keeps client order ids unique across restarts (default "
     "\"runs/session_epoch\")"},
    {"engine",
     "rng_seed",
     KeyType::Int,
     false,
     "seed of the strategy random generator ctx.rng() (default 1)"},
    {"engine",
     "md_ring_bytes",
     KeyType::Int,
     false,
     "market-data ring per venue, bytes, a power of two (default 4194304)"},
    {"engine",
     "order_ring_bytes",
     KeyType::Int,
     false,
     "order-event ring per venue, bytes, a power of two (default 1048576)"},
    {"engine",
     "journal_ring_bytes",
     KeyType::Int,
     false,
     "engine-to-journal ring, bytes, a power of two (default 16777216)"},
    {"engine",
     "max_events_per_step",
     KeyType::Int,
     false,
     "events taken from each ring per engine iteration (default 64)"},
    {"engine",
     "crossed_grace_ms",
     KeyType::Int,
     false,
     "tolerate a crossed book this long before pulling its quotes, ms (default 100)"},
    {"engine",
     "latency_publish_ms",
     KeyType::Int,
     false,
     "latency histogram publish interval, ms (default 1000)"},
    {"engine",
     "tsc_recalibrate_s",
     KeyType::Int,
     false,
     "fastmm-live: TSC recalibration period, s; 0 = off (default 10)"},
    {"engine",
     "min_requote_ticks",
     KeyType::Int,
     false,
     "keep a resting quote whose price is within this many ticks of the desired price (default 1)"},
    {"engine",
     "min_requote_interval_ms",
     KeyType::Int,
     false,
     "change the same quote slot at most this often, ms (default 50)"},
    {"engine",
     "min_qty_bps",
     KeyType::Int,
     false,
     "keep a resting quote whose remaining quantity covers this share of the desired quantity, "
     "bps (default 8000 = 80 %)"},
    {"engine", "post_only", KeyType::Bool, false, "send quotes as post-only orders (default true)"},
    {"engine",
     "supports_replace",
     KeyType::Bool,
     false,
     "let the quote manager amend orders in place where the venue supports it (default true)"},
    {"engine",
     "reject_backoff_ms",
     KeyType::Int,
     false,
     "after a venue reject other than a post-only cross, no new orders on that side for this "
     "long, doubling with each further reject, ms; 0 = off (default 1000)"},
    {"engine",
     "reject_backoff_max_ms",
     KeyType::Int,
     false,
     "cap of the doubling reject backoff, ms (default 60000)"},
    {"engine",
     "on_kill",
     KeyType::String,
     false,
     "fastmm-live after a kill switch the engine trips itself ([risk] max_loss, a full ring, every "
     "venue killed): exit (normal shutdown, exit code 6) | stay (keep running with quoting off) "
     "(default exit)"},
    // [venues.<name>]
    {"venues.*",
     "kind",
     KeyType::String,
     true,
     "connector: binance_spot (alias binance) | bybit (alias bybit_spot) | deribit | sim "
     "(fastmm-sim-exchange and backtest configs)"},
    {"venues.*", "ws_url", KeyType::String, false, "market-data WebSocket URL"},
    {"venues.*",
     "ws_api_url",
     KeyType::String,
     false,
     "order-entry WebSocket API URL, where the venue has one"},
    {"venues.*", "rest_url", KeyType::String, false, "REST base URL"},
    {"venues.*", "api_key", KeyType::String, false, "API key, written as \"${VARIABLE}\""},
    {"venues.*", "api_secret", KeyType::String, false, "API secret, written as \"${VARIABLE}\""},
    {"venues.*",
     "testnet",
     KeyType::Bool,
     false,
     "the endpoints are a testnet or demo environment (default true)"},
    {"venues.*",
     "supports_replace",
     KeyType::Bool,
     false,
     "the venue can amend an order in place (default false)"},
    {"venues.*",
     "insecure_tls",
     KeyType::Bool,
     false,
     "skip TLS certificate verification; local simulator only (default false)"},
    {"venues.*",
     "ca_file",
     KeyType::String,
     false,
     "extra CA certificate, for example tests/fixtures/tls/cert.pem for the local simulator"},
    {"venues.*",
     "recv_window_ms",
     KeyType::Int,
     false,
     "validity window of signed requests, ms (default 3000)"},
    {"venues.*",
     "fees",
     KeyType::Table,
     false,
     "[venues.<name>.fees] table: maker_bps and taker_bps, used for PnL"},
    {"venues.*.fees",
     "maker_bps",
     KeyType::Float,
     false,
     "maker fee, bps; negative = rebate (default 0)"},
    {"venues.*.fees", "taker_bps", KeyType::Float, false, "taker fee, bps (default 0)"},
    // connector-specific keys (passthrough to VenueSection::extra; see docs/reference/venues.md)
    {"venues.*",
     "stale_ms",
     KeyType::Int,
     false,
     "no traffic for this long marks the feed stale and pulls the venue's quotes, ms (default "
     "2000; "
     "deribit 10000)",
     true},
    {"venues.*",
     "dead_ms",
     KeyType::Int,
     false,
     "no traffic for this long forces a reconnect, ms; raised to a per-connector minimum "
     "(binance and bybit 45000, deribit 30000 by default)",
     true},
    {"venues.*", "order_api", KeyType::String, false, "order entry: ws (default) | rest", true},
    {"venues.*",
     "allow_offline_reference_data",
     KeyType::Bool,
     false,
     "start without REST reference data, using the configured tick and lot (default false)",
     true},
    {"venues.*",
     "cancel_on_order_channel_loss",
     KeyType::Bool,
     false,
     "cancel all orders over REST when order entry drops (default true)",
     true},
    {"venues.*",
     "emit_ack_from_response",
     KeyType::Bool,
     false,
     "acknowledge orders from the request response, not the event stream (default true)",
     true},
    {"venues.*",
     "depth_limit",
     KeyType::Int,
     false,
     "binance: REST snapshot depth, 5 to 5000",
     true},
    {"venues.*", "key_type", KeyType::String, false, "binance: hmac (default) | ed25519", true},
    {"venues.*",
     "private_key_file",
     KeyType::String,
     false,
     "binance: Ed25519 private key file (PEM), with key_type = ed25519",
     true},
    {"venues.*",
     "user_stream",
     KeyType::String,
     false,
     "binance: ws_api (default) | listen_key | none",
     true},
    {"venues.*",
     "position_from_balance",
     KeyType::Bool,
     false,
     "binance: derive positions from account balances",
     true},
    {"venues.*",
     "depth",
     KeyType::Int,
     false,
     "bybit: order book subscription depth, 1 to 1000",
     true},
    {"venues.*",
     "ws_private_url",
     KeyType::String,
     false,
     "bybit, deribit: private WebSocket URL; empty = derived from ws_url",
     true},
    {"venues.*",
     "ping_interval_ms",
     KeyType::Int,
     false,
     "bybit: application ping interval, ms, at least 1000",
     true},
    {"venues.*",
     "orders_per_second",
     KeyType::Int,
     false,
     "bybit: client-side order rate cap, orders/s",
     true},
    {"venues.*",
     "position_from_wallet",
     KeyType::Bool,
     false,
     "bybit: derive positions from the wallet",
     true},
    {"venues.*",
     "currencies",
     KeyType::Any,
     false,
     "deribit: currencies for reference data, user channels and reconciliation, \"BTC\" or "
     "[\"BTC\", \"ETH\"] (default \"BTC\")",
     true},
    {"venues.*",
     "book_interval",
     KeyType::String,
     false,
     "deribit: book channel interval, 100ms (default) | agg2",
     true},
    {"venues.*",
     "ticker_interval",
     KeyType::String,
     false,
     "deribit: ticker channel interval, 100ms (default) | agg2",
     true},
    {"venues.*",
     "trades_interval",
     KeyType::String,
     false,
     "deribit: trades channel interval, 100ms (default) | agg2",
     true},
    {"venues.*",
     "heartbeat_interval_s",
     KeyType::Int,
     false,
     "deribit: public/set_heartbeat interval, s, at least 10",
     true},
    {"venues.*",
     "reject_post_only",
     KeyType::Bool,
     false,
     "deribit: reject crossing post-only orders instead of repricing them (default true)",
     true},
    {"venues.*",
     "cancel_on_disconnect",
     KeyType::Bool,
     false,
     "deribit: cancel-on-disconnect on the order connection (default true)",
     true},
    {"venues.*",
     "matching_engine_rate",
     KeyType::Int,
     false,
     "deribit: order requests per second of the account tier (default 5)",
     true},
    {"venues.*",
     "matching_engine_burst",
     KeyType::Int,
     false,
     "deribit: order request burst of the account tier (default 20)",
     true},
    // [[instruments]]
    {"instruments[]", "venue", KeyType::String, true, "name of a [venues.<name>] table"},
    {"instruments[]", "symbol", KeyType::String, true, "venue symbol, for example BTCUSDT"},
    {"instruments[]", "base", KeyType::String, false, "base asset, for example BTC"},
    {"instruments[]", "quote", KeyType::String, false, "quote asset, for example USDT"},
    {"instruments[]",
     "asset_class",
     KeyType::String,
     false,
     "spot | perpetual (perp) | future (futures) | option | fx | equity (default spot)"},
    {"instruments[]", "tick", KeyType::Any, true, "price increment, decimal"},
    {"instruments[]", "lot", KeyType::Any, true, "quantity increment, decimal"},
    {"instruments[]", "min_qty", KeyType::Any, false, "smallest order quantity, decimal"},
    {"instruments[]", "max_qty", KeyType::Any, false, "largest order quantity, decimal"},
    {"instruments[]",
     "min_notional",
     KeyType::Any,
     false,
     "smallest order value, quote currency, decimal"},
    {"instruments[]",
     "contract_multiplier",
     KeyType::Any,
     false,
     "units of the underlying per contract, decimal; PnL and notional use it (default 1)"},
    {"instruments[]",
     "enabled",
     KeyType::Bool,
     false,
     "trade this instrument; false loads it without trading (default true)"},
    {"instruments[]", "price_decimals", KeyType::Int, false, "price display precision (default 8)"},
    {"instruments[]", "expiry", KeyType::String, false, "expiry of a derivative, ISO-8601"},
    {"instruments[]", "strike", KeyType::Any, false, "option strike, decimal"},
    {"instruments[]", "option_type", KeyType::String, false, "call | put"},
    // [strategy]
    {"strategy", "name", KeyType::String, true, "registered strategy name (see --list-strategies)"},
    {"strategy",
     "max_param_age_ms",
     KeyType::Int,
     false,
     "disable quoting before the first parameter update and while none was applied for this long, "
     "ms of engine time (default 0: off)"},
    {"strategy",
     "params",
     KeyType::Table,
     false,
     "[strategy.params] table: the strategy's parameters"},
    {"strategy.params", "*", KeyType::Any, false, "strategy parameters (validated by the schema)"},
    // [risk]
    {"risk", "max_order_qty", KeyType::Any, false, "largest order quantity, decimal"},
    {"risk",
     "max_order_notional",
     KeyType::Any,
     false,
     "largest order value, quote currency, decimal"},
    {"risk",
     "max_position",
     KeyType::Any,
     false,
     "largest absolute position per instrument, counting same-side open orders, decimal"},
    {"risk", "max_open_orders", KeyType::Int, false, "open orders per instrument"},
    {"risk",
     "price_collar_bps",
     KeyType::Int,
     false,
     "refuse limit prices further than this from the mid, bps"},
    {"risk",
     "fat_finger_bps",
     KeyType::Int,
     false,
     "refuse limit prices further than this from the last trade, bps"},
    {"risk",
     "stale_md_ms",
     KeyType::Int,
     false,
     "refuse orders when the instrument's book is older than this, ms"},
    {"risk",
     "max_loss",
     KeyType::Any,
     false,
     "trip the kill switch when net PnL falls to -max_loss, quote currency, decimal"},
    {"risk", "orders_per_sec", KeyType::Int, false, "token-bucket order rate, orders/s"},
    {"risk",
     "burst",
     KeyType::Int,
     false,
     "token-bucket capacity, orders (default orders_per_sec)"},
    {"risk",
     "stp",
     KeyType::Bool,
     false,
     "self-trade prevention against our own resting orders (default true)"},
    // [logging]
    {"logging",
     "level",
     KeyType::String,
     false,
     "trace | debug | info | warn (or warning) | error | off (default info)"},
    {"logging", "file", KeyType::String, false, "log file; empty = stderr only"},
    {"logging",
     "mirror_level",
     KeyType::String,
     false,
     "records at or above this level are also written to stderr (default warn)"},
    // free-form
    {"sim", "*", KeyType::Any, false, "simulator settings"},
    {"sim.*", "*", KeyType::Any, false, "simulator sub-tables"},
    {"backtest", "*", KeyType::Any, false, "backtester settings"},
    {"backtest.*", "*", KeyType::Any, false, "backtester sub-tables"},
};

[[nodiscard]] inline std::span<const KeySpec> config_schema() noexcept {
  return kConfigSchema;
}

}  // namespace fastmm
