#pragma once
// Declarative config schema (8.7): every known key with its section, type and whether it
// is required. config.cpp validates the parsed TOML against this table and reports
// errors with line numbers; unknown keys are warnings so configs stay forward compatible.
// Sections "sim", "backtest" and "storage" are free-form (owned by the sim, backtest and store
// libraries), and a [venues.<name>] key this table does not list belongs to the connector its
// `kind` names: the venue declares, validates and documents it
// (include/fastmm/venues/registry.hpp).
//
// The doc strings are the key tables of docs/reference/configuration.md
// (python3 tools/docs_config_ref.py regenerates them): say what the key does, its unit and its
// default.
#include <cstddef>
#include <span>
#include <string_view>

namespace fastmm {

enum class KeyType : unsigned char { String, Int, Float, Bool, IntArray, StringArray, Table, Any };

struct KeySpec {
  std::string_view section;  // "engine", "venues.*", "instruments[]", "strategy", ...
  std::string_view key;
  KeyType type;
  bool required;
  std::string_view doc;
};

inline constexpr KeySpec kConfigSchema[] = {
    // [engine]
    {"engine",
     "name",
     KeyType::String,
     false,
     "session name, used in logs, journal file names and the status file (default \"fastmm\")"},
    {"engine",
     "cpu",
     KeyType::Int,
     false,
     "CPU core of the engine thread; -1 = not pinned (default -1)"},
    {"engine",
     "net_cpus",
     KeyType::IntArray,
     false,
     "CPU cores of the network threads, one per venue in order (default [])"},
    {"engine",
     "spin_mode",
     KeyType::String,
     false,
     "busy (spin forever) | adaptive (spin briefly, then block until work arrives; use on WSL2 "
     "and laptops) (default adaptive)"},
    {"engine",
     "net_backend",
     KeyType::String,
     false,
     "event loop of fastmm-live and fastmm-sim-exchange: epoll | io_uring (Linux 5.13 or newer; "
     "falls back to epoll with a warning) (default epoll)"},
    {"engine",
     "threading",
     KeyType::String,
     false,
     "fastmm-live: split (engine and network threads, rings between them) | single (one venue; "
     "its network loop, the engine and order sending run on the engine thread, cpu; net_cpus is "
     "ignored) (default split)"},
    {"engine",
     "journal",
     KeyType::Bool,
     false,
     "record every consumed event to a .fmj journal (default true)"},
    {"engine", "journal_dir", KeyType::String, false, "directory for journals (default \"runs\")"},
    {"engine",
     "journal_sync",
     KeyType::String,
     false,
     "how far a journal write is pushed: async (msync every 100 ms; survives the process dying) | "
     "fdatasync (msync + fdatasync on the same tick; survives power loss) (default async)"},
    {"engine",
     "journal_max_bytes",
     KeyType::Int,
     false,
     "roll the journal over to the next part at this size, bytes; each part is a complete journal "
     "(\"x.fmj\", \"x.1.fmj\", ...); 0 = one file per session (default 0)"},
    {"engine",
     "journal_retention_days",
     KeyType::Int,
     false,
     "delete .fmj files in journal_dir last written more than this many days ago, at start; "
     "0 = keep everything (default 0)"},
    {"engine",
     "epoch_file",
     KeyType::String,
     false,
     "session epoch file, keeps client order ids unique across restarts (default "
     "\"runs/session_epoch\")"},
    {"engine",
     "kill_file",
     KeyType::String,
     false,
     "latched kill switch and cumulative PnL, so [risk] max_loss is a budget across restarts "
     "(default \"<journal_dir>/<name>.kill\")"},
    {"engine",
     "ack_timeout_ms",
     KeyType::Int,
     false,
     "force-cancel an order whose ack has not arrived within this long, ms; 0 = off (default 0)"},
    {"engine",
     "queue_conservatism",
     KeyType::Float,
     false,
     "the queue position estimate ctx.queue_ahead, from 0 to 1: at 0 a level's shrink is shared "
     "between cancels ahead of and behind our order, at 1 cancels never move it up (default 1.0; "
     "a backtest uses [backtest] queue_conservatism when set)"},
    {"engine",
     "flatten_interval_ms",
     KeyType::Int,
     false,
     "how often an operator flatten looks at the position left and sends the next reduce-only "
     "slice, ms (default 500)"},
    {"engine",
     "flatten_timeout_ms",
     KeyType::Int,
     false,
     "how long an operator flatten keeps trying before it gives up and leaves the position, ms; "
     "0 = until it is flat or an operator stops it (default 60000)"},
    {"engine",
     "flatten_slippage_bps",
     KeyType::Int,
     false,
     "how far through the touch a flatten prices its orders when the command gives no "
     "--max-slippage-bps, basis points (default 25)"},
    {"engine",
     "rng_seed",
     KeyType::Int,
     false,
     "seed of the strategy random generator ctx.rng() (default 1)"},
    {"engine",
     "md_ring_bytes",
     KeyType::Int,
     false,
     "market-data ring per venue, bytes, a power of two (default 4194304)"},
    {"engine",
     "order_ring_bytes",
     KeyType::Int,
     false,
     "order-event ring per venue, bytes, a power of two (default 1048576)"},
    {"engine",
     "journal_ring_bytes",
     KeyType::Int,
     false,
     "engine-to-journal ring, bytes, a power of two (default 16777216)"},
    {"engine",
     "max_events_per_step",
     KeyType::Int,
     false,
     "events taken from each ring per engine iteration (default 64)"},
    {"engine",
     "crossed_grace_ms",
     KeyType::Int,
     false,
     "tolerate a crossed book this long before pulling its quotes, ms (default 100)"},
    {"engine",
     "latency_publish_ms",
     KeyType::Int,
     false,
     "latency histogram publish interval, ms (default 1000)"},
    {"engine",
     "tsc_recalibrate_s",
     KeyType::Int,
     false,
     "fastmm-live: TSC recalibration period, s; 0 = off (default 10)"},
    {"engine",
     "timer_slack_ns",
     KeyType::Int,
     false,
     "fastmm-live: timer slack of its threads, ns; how late a timed wait may end (adaptive "
     "spin_mode: the engine's idle wait, at most 1 ms, and with threading = \"single\" a 50 us "
     "sleep); 0 = the kernel's, 50000 (default 0)"},
    {"engine",
     "restore_position",
     KeyType::Bool,
     false,
     "carry the previous session's positions over from the store and replay the venue's executions "
     "since its last recorded fill (venues that can replay executions); default true"},
    {"engine",
     "lock_memory",
     KeyType::Bool,
     false,
     "fastmm-live: mlockall() the process, so no page is swapped out or faulted in on the hot "
     "path; needs ulimit -l above the process size, a warning otherwise (default false)"},
    {"engine",
     "min_requote_ticks",
     KeyType::Int,
     false,
     "keep a resting quote whose price is within this many ticks of the desired price (default 1)"},
    {"engine",
     "min_requote_interval_ms",
     KeyType::Int,
     false,
     "change the same quote slot at most this often, ms (default 50)"},
    {"engine",
     "min_qty_bps",
     KeyType::Int,
     false,
     "keep a resting quote whose remaining quantity covers this share of the desired quantity, "
     "bps (default 8000 = 80 %)"},
    {"engine", "post_only", KeyType::Bool, false, "send quotes as post-only orders (default true)"},
    {"engine",
     "supports_replace",
     KeyType::Bool,
     false,
     "let the quote manager amend orders in place where the venue supports it (default true)"},
    {"engine",
     "reject_backoff_ms",
     KeyType::Int,
     false,
     "after a venue reject other than a post-only cross, no new orders on that side for this "
     "long, doubling with each further reject, ms; 0 = off (default 1000)"},
    {"engine",
     "reject_backoff_max_ms",
     KeyType::Int,
     false,
     "cap of the doubling reject backoff, ms (default 60000)"},
    {"engine",
     "on_kill",
     KeyType::String,
     false,
     "fastmm-live after a kill switch the engine trips itself ([risk] max_loss, a full ring, every "
     "venue killed): exit (normal shutdown, exit code 6) | stay (keep running with quoting off) "
     "(default exit)"},
    // [venues.<name>]
    {"venues.*",
     "kind",
     KeyType::String,
     true,
     "name of a registered connector; the keys it adds to this section are its own "
     "(see Connectors below)"},
    {"venues.*", "ws_url", KeyType::String, false, "market-data WebSocket URL"},
    {"venues.*",
     "ws_api_url",
     KeyType::String,
     false,
     "order-entry WebSocket API URL, where the venue has one"},
    {"venues.*", "rest_url", KeyType::String, false, "REST base URL"},
    {"venues.*", "api_key", KeyType::String, false, "API key, written as \"${VARIABLE}\""},
    {"venues.*", "api_secret", KeyType::String, false, "API secret, written as \"${VARIABLE}\""},
    {"venues.*",
     "api_passphrase",
     KeyType::String,
     false,
     "API key passphrase where the venue has one (OKX), written as \"${VARIABLE}\""},
    {"venues.*",
     "testnet",
     KeyType::Bool,
     false,
     "the endpoints are a testnet or demo environment (default true)"},
    {"venues.*",
     "supports_replace",
     KeyType::Bool,
     false,
     "the venue can amend an order in place (default false)"},
    {"venues.*",
     "insecure_tls",
     KeyType::Bool,
     false,
     "skip TLS certificate verification; local simulator only (default false)"},
    {"venues.*",
     "ca_file",
     KeyType::String,
     false,
     "extra CA certificate, for example tests/fixtures/tls/cert.pem for the local simulator"},
    {"venues.*",
     "recv_window_ms",
     KeyType::Int,
     false,
     "validity window of signed requests, ms (default 3000)"},
    {"venues.*",
     "fees",
     KeyType::Table,
     false,
     "[venues.<name>.fees] table: maker_bps and taker_bps, used for PnL"},
    {"venues.*.fees",
     "maker_bps",
     KeyType::Float,
     false,
     "maker fee, bps; negative = rebate (default 0)"},
    {"venues.*.fees", "taker_bps", KeyType::Float, false, "taker fee, bps (default 0)"},
    // [[instruments]]
    {"instruments[]", "venue", KeyType::String, true, "name of a [venues.<name>] table"},
    {"instruments[]", "symbol", KeyType::String, true, "venue symbol, for example BTCUSDT"},
    {"instruments[]", "base", KeyType::String, false, "base asset, for example BTC"},
    {"instruments[]", "quote", KeyType::String, false, "quote asset, for example USDT"},
    {"instruments[]",
     "asset_class",
     KeyType::String,
     false,
     "spot | perpetual (perp) | future (futures) | option | fx | equity (default spot)"},
    {"instruments[]", "tick", KeyType::Any, true, "price increment, decimal"},
    {"instruments[]", "lot", KeyType::Any, true, "quantity increment, decimal"},
    {"instruments[]", "min_qty", KeyType::Any, false, "smallest order quantity, decimal"},
    {"instruments[]", "max_qty", KeyType::Any, false, "largest order quantity, decimal"},
    {"instruments[]",
     "min_notional",
     KeyType::Any,
     false,
     "smallest order value, settlement currency (base coin for an inverse contract), "
     "decimal"},
    {"instruments[]",
     "contract_multiplier",
     KeyType::Any,
     false,
     "units of the underlying per contract, decimal; PnL and notional use it (default 1)"},
    {"instruments[]",
     "enabled",
     KeyType::Bool,
     false,
     "trade this instrument; false loads it without trading (default true)"},
    {"instruments[]", "price_decimals", KeyType::Int, false, "price display precision (default 8)"},
    {"instruments[]", "expiry", KeyType::String, false, "expiry of a derivative, ISO-8601"},
    {"instruments[]", "strike", KeyType::Any, false, "option strike, decimal"},
    {"instruments[]", "option_type", KeyType::String, false, "call | put"},
    {"instruments[]",
     "maker_bps",
     KeyType::Float,
     false,
     "maker fee of this instrument, bps; negative = rebate. Overrides the venue's fees table"},
    {"instruments[]",
     "taker_bps",
     KeyType::Float,
     false,
     "taker fee of this instrument, bps. Overrides the venue's fees table"},
    // [strategy]
    {"strategy", "name", KeyType::String, true, "registered strategy name (see --list-strategies)"},
    {"strategy",
     "max_param_age_ms",
     KeyType::Int,
     false,
     "disable quoting before the first parameter update and while none was applied for this long, "
     "ms of engine time (default 0: off)"},
    {"strategy",
     "params",
     KeyType::Table,
     false,
     "[strategy.params] table: the strategy's parameters"},
    {"strategy.params", "*", KeyType::Any, false, "strategy parameters (validated by the schema)"},
    // [risk]
    {"risk", "max_order_qty", KeyType::Any, false, "largest order quantity, decimal"},
    {"risk",
     "max_order_notional",
     KeyType::Any,
     false,
     "largest order value, settlement currency (base coin for an inverse contract), decimal"},
    {"risk",
     "max_position",
     KeyType::Any,
     false,
     "largest absolute position per instrument, counting same-side open orders, decimal"},
    {"risk", "max_open_orders", KeyType::Int, false, "open orders per instrument"},
    {"risk",
     "price_collar_bps",
     KeyType::Int,
     false,
     "refuse limit prices further than this from the mid, bps"},
    {"risk",
     "fat_finger_bps",
     KeyType::Int,
     false,
     "refuse limit prices further than this from the last trade, bps"},
    {"risk",
     "stale_md_ms",
     KeyType::Int,
     false,
     "refuse orders when the instrument's book is older than this, ms"},
    {"risk",
     "max_loss",
     KeyType::Any,
     false,
     "trip the kill switch when net PnL falls to -max_loss, settlement currency (the "
     "[accounting] reporting_currency when set), decimal; latched across restarts in kill_file"},
    {"risk",
     "max_gross_notional",
     KeyType::Any,
     false,
     "refuse an order that would take the portfolio's summed |position| at the last marks past "
     "this, settlement currency (or reporting_currency), decimal"},
    {"risk",
     "max_net_notional",
     KeyType::Any,
     false,
     "refuse an order that would take the portfolio's signed position sum further past this, "
     "settlement currency (or reporting_currency), decimal"},
    {"risk", "orders_per_sec", KeyType::Int, false, "token-bucket order rate, orders/s"},
    {"risk",
     "burst",
     KeyType::Int,
     false,
     "token-bucket capacity, orders (default orders_per_sec)"},
    {"risk",
     "stp",
     KeyType::Bool,
     false,
     "self-trade prevention against our own resting orders (default true)"},
    {"risk",
     "max_feed_lag_ms",
     KeyType::Int,
     false,
     "pull a venue's quotes and refuse orders that could rest there without reducing the "
     "position while its market data arrives this much later than its baseline, ms; resumes "
     "100 ms after the last message over it (default 0: off)"},
    // [gateway]
    {"gateway",
     "orders_per_sec",
     KeyType::Int,
     false,
     "fastmm-gateway: new orders and replaces per second per venue, over every attached strategy "
     "(default 0: off)"},
    {"gateway",
     "burst",
     KeyType::Int,
     false,
     "fastmm-gateway: token-bucket capacity of orders_per_sec, orders (default orders_per_sec)"},
    {"gateway",
     "max_open_notional",
     KeyType::Any,
     false,
     "fastmm-gateway: refuse an order that would take the notional working at its venue, over "
     "every attached strategy and both sides, past this; settlement currency, decimal"},
    {"gateway",
     "max_loss",
     KeyType::Any,
     false,
     "fastmm-gateway: trip the account's kill switch when the net PnL of every strategy together, "
     "carried across restarts in the gateway's kill file, reaches -max_loss; decimal, in "
     "[accounting] reporting_currency when set"},
    {"gateway",
     "max_gross_notional",
     KeyType::Any,
     false,
     "fastmm-gateway: refuse an order that would take the sum of the account's |position| at the "
     "marks past this, unless it reduces its instrument's position; decimal"},
    {"gateway",
     "max_net_notional",
     KeyType::Any,
     false,
     "fastmm-gateway: refuse an order that would take the account's net position at the marks "
     "further past this, unless it reduces its instrument's position; decimal"},
    // [accounting]
    {"accounting",
     "reporting_currency",
     KeyType::String,
     false,
     "currency the PnL totals, [risk] max_loss and the exposure caps (and fastmm-gateway's) are in "
     "when instruments settle in more than one; every other settlement currency needs a source in "
     "[accounting.fx] (default unset: no conversion)"},
    {"accounting",
     "fx",
     KeyType::Table,
     false,
     "[accounting.fx] table: one entry per other settlement currency, the instrument whose mid "
     "prices it in reporting_currency (BTC = \"binance:BTCUSDT\"; a pair quoted the other way "
     "round, USDTBTC, is inverted)"},
    {"accounting.fx", "*", KeyType::String, false, "FX source of one settlement currency"},
    // [logging]
    {"logging",
     "level",
     KeyType::String,
     false,
     "trace | debug | info | warn (or warning) | error | off (default info)"},
    {"logging", "file", KeyType::String, false, "log file; empty = stderr only"},
    {"logging",
     "mirror_level",
     KeyType::String,
     false,
     "records at or above this level are also written to stderr (default warn)"},
    // free-form
    {"sim", "*", KeyType::Any, false, "simulator settings"},
    {"sim.*", "*", KeyType::Any, false, "simulator sub-tables"},
    {"backtest", "*", KeyType::Any, false, "backtester settings"},
    {"backtest.*", "*", KeyType::Any, false, "backtester sub-tables"},
};

[[nodiscard]] inline std::span<const KeySpec> config_schema() noexcept {
  return kConfigSchema;
}

}  // namespace fastmm
