#pragma once
// fastmm::codecs::sbe: runtime support for the flyweights generated by tools/sbe_gen.py.
//
// Simple Binary Encoding 1.0 (FIX Trading Community). Everything here reads and writes through
// memcpy at explicit offsets: no packed-struct casts, so alignment and strict aliasing never come
// into play and the compiler still folds each accessor into a single load. Nothing allocates,
// throws or is virtual.
//
//   MessageHeader     blockLength, templateId, schemaId, version (8 bytes, little-endian)
//   GroupView<E, D>   read-only repeating group: bounds-checked once, then O(1) entry access
//   GroupWriter<E, D> writes a group dimension header and hands out entry writers
//   VarData           one length-prefixed <data> field (Binance: the trailing symbol)
//   Decimal<M, e>     mantissa with a constant exponent (CME PRICE9 = int64 x 10^-9); converts
//                     exactly to and from the engine's 1e-8 fixed point, or reports failure
#include "fastmm/core/config_macros.hpp"
#include "fastmm/core/fixed_point.hpp"

#include <bit>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <span>
#include <string_view>
#include <type_traits>

namespace fastmm::codecs::sbe {

// SBE schemas used here are little-endian and FastMM targets x86-64; a big-endian port would
// byte-swap in load_le/store_le.
static_assert(std::endian::native == std::endian::little, "sbe: little-endian hosts only");

template <class T>
  requires std::is_trivially_copyable_v<T>
[[nodiscard]] FASTMM_FORCE_INLINE T load_le(const std::byte* p) noexcept {
  T v;
  std::memcpy(&v, p, sizeof(T));
  return v;
}

template <class T>
  requires std::is_trivially_copyable_v<T>
FASTMM_FORCE_INLINE void store_le(std::byte* p, T v) noexcept {
  std::memcpy(p, &v, sizeof(T));
}

// Fixed-length char array: the value ends at the first NUL (SBE pads with NUL).
[[nodiscard]] inline std::string_view load_chars(const std::byte* p, std::size_t n) noexcept {
  const auto* s = reinterpret_cast<const char*>(p);
  const auto* nul = static_cast<const char*>(std::memchr(s, 0, n));
  return {s, nul == nullptr ? n : static_cast<std::size_t>(nul - s)};
}

// Copies at most n chars and NUL-pads the rest.
inline void store_chars(std::byte* p, std::size_t n, std::string_view v) noexcept {
  const std::size_t k = v.size() < n ? v.size() : n;
  if (k != 0) std::memcpy(p, v.data(), k);
  if (k < n) std::memset(p + k, 0, n - k);
}

struct MessageHeader {
  static constexpr std::size_t kSize = 8;
  std::uint16_t block_length = 0;
  std::uint16_t template_id = 0;
  std::uint16_t schema_id = 0;
  std::uint16_t version = 0;

  [[nodiscard]] static MessageHeader load(const std::byte* p) noexcept {
    return MessageHeader{load_le<std::uint16_t>(p),
                         load_le<std::uint16_t>(p + 2),
                         load_le<std::uint16_t>(p + 4),
                         load_le<std::uint16_t>(p + 6)};
  }
  void store(std::byte* p) const noexcept {
    store_le(p, block_length);
    store_le(p + 2, template_id);
    store_le(p + 4, schema_id);
    store_le(p + 6, version);
  }
  constexpr bool operator==(const MessageHeader&) const noexcept = default;
};

// ---- decimals ---------------------------------------------------------------------------------

inline constexpr std::int64_t kPow10[19] = {1LL,
                                            10LL,
                                            100LL,
                                            1'000LL,
                                            10'000LL,
                                            100'000LL,
                                            1'000'000LL,
                                            10'000'000LL,
                                            100'000'000LL,
                                            1'000'000'000LL,
                                            10'000'000'000LL,
                                            100'000'000'000LL,
                                            1'000'000'000'000LL,
                                            10'000'000'000'000LL,
                                            100'000'000'000'000LL,
                                            1'000'000'000'000'000LL,
                                            10'000'000'000'000'000LL,
                                            100'000'000'000'000'000LL,
                                            1'000'000'000'000'000'000LL};

// mantissa * 10^exponent expressed as a raw 1e-8 fixed-point value. False when the result
// would lose precision (digits beyond 1e-8) or overflow int64.
[[nodiscard]] constexpr bool decimal_to_fixed_raw(std::int64_t mantissa,
                                                  int exponent,
                                                  std::int64_t& raw) noexcept {
  const int shift = exponent + kFixedDecimals;
  if (mantissa == 0) {
    raw = 0;
    return true;
  }
  if (shift >= 0) {
    if (shift > 18) return false;
    return !__builtin_mul_overflow(mantissa, kPow10[shift], &raw);
  }
  if (-shift > 18) return false;
  const std::int64_t d = kPow10[-shift];
  if (mantissa % d != 0) return false;
  raw = mantissa / d;
  return true;
}

// Inverse of decimal_to_fixed_raw: the mantissa for `raw` at `exponent`, false if inexact or
// out of range.
[[nodiscard]] constexpr bool fixed_raw_to_decimal(std::int64_t raw,
                                                  int exponent,
                                                  std::int64_t& mantissa) noexcept {
  const int shift = exponent + kFixedDecimals;
  if (raw == 0) {
    mantissa = 0;
    return true;
  }
  if (shift <= 0) {
    if (-shift > 18) return false;
    return !__builtin_mul_overflow(raw, kPow10[-shift], &mantissa);
  }
  if (shift > 18) return false;
  const std::int64_t d = kPow10[shift];
  if (raw % d != 0) return false;
  mantissa = raw / d;
  return true;
}

template <class M, int kExp, bool kOptional, M kNull>
  requires std::is_integral_v<M> && std::is_signed_v<M>
struct Decimal {
  static constexpr std::size_t kSize = sizeof(M);
  static constexpr int kExponent = kExp;
  static constexpr bool kIsOptional = kOptional;
  static constexpr M kNullMantissa = kNull;

  M mantissa = 0;

  [[nodiscard]] static constexpr Decimal null() noexcept { return Decimal{kNull}; }
  [[nodiscard]] constexpr bool is_null() const noexcept { return kOptional && mantissa == kNull; }
  [[nodiscard]] static Decimal load(const std::byte* p) noexcept { return Decimal{load_le<M>(p)}; }
  void store(std::byte* p) const noexcept { store_le<M>(p, mantissa); }

  // Exact conversion to 1e-8 fixed point. False for null, precision loss or overflow.
  template <class Tag>
  [[nodiscard]] constexpr bool to_fixed(Fixed<Tag>& out) const noexcept {
    std::int64_t raw = 0;
    if (is_null() || !decimal_to_fixed_raw(static_cast<std::int64_t>(mantissa), kExp, raw)) {
      return false;
    }
    out = Fixed<Tag>::from_raw(raw);
    return true;
  }
  // Exact conversion from fixed point. False if inexact, out of range, or equal to the null
  // mantissa of an optional type.
  template <class Tag>
  [[nodiscard]] static constexpr bool from_fixed(Fixed<Tag> v, Decimal& out) noexcept {
    std::int64_t m = 0;
    if (!fixed_raw_to_decimal(v.raw, kExp, m)) return false;
    if (m < static_cast<std::int64_t>(std::numeric_limits<M>::min()) ||
        m > static_cast<std::int64_t>(std::numeric_limits<M>::max())) {
      return false;
    }
    out.mantissa = static_cast<M>(m);
    return !out.is_null();
  }
  constexpr bool operator==(const Decimal&) const noexcept = default;
};

// ---- repeating groups -------------------------------------------------------------------------

// Read-only view of one repeating group. `Dim` is a generated dimension description
// (kSize, kBlockLengthOffset, BlockLength, kNumInGroupOffset, NumInGroup). The constructor checks
// once that the dimension header and every entry fit in the buffer and that each entry is at
// least as long as the fields the schema requires; entries use the ACTING block length as the
// stride, so blocks extended by a newer schema version are skipped correctly.
template <class Entry, class Dim>
class GroupView {
 public:
  GroupView() noexcept = default;
  // p: start of the dimension header; avail: readable bytes from p; offset: p's offset inside
  // the message body (lets the next group chain from end_offset()).
  GroupView(const std::byte* p,
            std::size_t avail,
            std::size_t offset,
            std::uint16_t version,
            std::uint16_t required_block_length) noexcept
      : offset_(offset), version_(version) {
    if (avail < Dim::kSize) return;
    const std::size_t bl = load_le<typename Dim::BlockLength>(p + Dim::kBlockLengthOffset);
    const std::size_t n = load_le<typename Dim::NumInGroup>(p + Dim::kNumInGroupOffset);
    if (Dim::kSize + bl * n > avail) return;
    if (n != 0 && bl < required_block_length) return;
    p_ = p + Dim::kSize;
    block_length_ = static_cast<std::uint16_t>(bl);
    count_ = n;
    valid_ = true;
  }

  [[nodiscard]] bool valid() const noexcept { return valid_; }
  [[nodiscard]] std::size_t count() const noexcept { return count_; }
  [[nodiscard]] bool empty() const noexcept { return count_ == 0; }
  [[nodiscard]] std::uint16_t block_length() const noexcept { return block_length_; }
  [[nodiscard]] std::size_t offset() const noexcept { return offset_; }
  [[nodiscard]] std::size_t size_bytes() const noexcept {
    return valid_ ? Dim::kSize + std::size_t{block_length_} * count_ : 0;
  }
  [[nodiscard]] std::size_t end_offset() const noexcept { return offset_ + size_bytes(); }

  [[nodiscard]] Entry operator[](std::size_t i) const noexcept {
    FASTMM_ASSERT(i < count_);
    return Entry(p_ + i * block_length_, block_length_, version_);
  }

  class iterator {
   public:
    iterator(const GroupView* g, std::size_t i) noexcept : g_(g), i_(i) {}
    Entry operator*() const noexcept { return (*g_)[i_]; }
    iterator& operator++() noexcept {
      ++i_;
      return *this;
    }
    bool operator==(const iterator& o) const noexcept { return i_ == o.i_; }

   private:
    const GroupView* g_;
    std::size_t i_;
  };
  [[nodiscard]] iterator begin() const noexcept { return iterator(this, 0); }
  [[nodiscard]] iterator end() const noexcept { return iterator(this, count_); }

 private:
  const std::byte* p_ = nullptr;
  std::size_t count_ = 0;
  std::size_t offset_ = 0;
  std::uint16_t block_length_ = 0;
  std::uint16_t version_ = 0;
  bool valid_ = false;
};

// ---- variable-length data ---------------------------------------------------------------------

// One <data> field: a length prefix of type L followed by that many bytes. `offset` is where the
// prefix starts inside the message body; the next data field starts at end_offset().
class VarData {
 public:
  VarData() noexcept = default;

  template <class L>
    requires std::is_unsigned_v<L>
  [[nodiscard]] static VarData load(const std::byte* body,
                                    std::size_t size,
                                    std::size_t at) noexcept {
    VarData d;
    if (at > size || size - at < sizeof(L)) return d;
    const std::size_t n = load_le<L>(body + at);
    if (size - at - sizeof(L) < n) return d;
    d.data_ = reinterpret_cast<const char*>(body + at + sizeof(L));
    d.size_ = n;
    d.end_ = at + sizeof(L) + n;
    d.valid_ = true;
    return d;
  }
  // Writes the prefix and bytes at p; returns the bytes used, 0 if they do not fit in `cap` or
  // v is longer than L can express.
  template <class L>
    requires std::is_unsigned_v<L>
  [[nodiscard]] static std::size_t store(std::byte* p,
                                         std::size_t cap,
                                         std::string_view v) noexcept {
    if (v.size() > std::numeric_limits<L>::max() || cap < sizeof(L) + v.size()) return 0;
    store_le<L>(p, static_cast<L>(v.size()));
    if (!v.empty()) std::memcpy(p + sizeof(L), v.data(), v.size());
    return sizeof(L) + v.size();
  }

  [[nodiscard]] bool valid() const noexcept { return valid_; }
  [[nodiscard]] std::string_view value() const noexcept { return {data_, size_}; }
  [[nodiscard]] std::size_t end_offset() const noexcept { return end_; }

 private:
  const char* data_ = nullptr;
  std::size_t size_ = 0;
  std::size_t end_ = 0;
  bool valid_ = false;
};

template <class EntryWriter, class Dim>
class GroupWriter {
 public:
  GroupWriter() noexcept = default;

  // Writes the dimension header at p and zero-fills `count` entries. Not ok() (and nothing is
  // written) when the group does not fit in `cap` bytes or count exceeds NumInGroup.
  [[nodiscard]] static GroupWriter create(std::byte* p,
                                          std::size_t cap,
                                          std::uint16_t block_length,
                                          std::size_t count) noexcept {
    GroupWriter g;
    if (p == nullptr || count > std::numeric_limits<typename Dim::NumInGroup>::max()) return g;
    const std::size_t need = Dim::kSize + std::size_t{block_length} * count;
    if (need > cap) return g;
    std::memset(p, 0, need);
    store_le<typename Dim::BlockLength>(p + Dim::kBlockLengthOffset, block_length);
    store_le<typename Dim::NumInGroup>(p + Dim::kNumInGroupOffset,
                                       static_cast<typename Dim::NumInGroup>(count));
    g.p_ = p + Dim::kSize;
    g.count_ = count;
    g.block_length_ = block_length;
    g.ok_ = true;
    return g;
  }

  [[nodiscard]] bool ok() const noexcept { return ok_; }
  [[nodiscard]] std::size_t count() const noexcept { return count_; }
  [[nodiscard]] std::size_t size_bytes() const noexcept {
    return ok_ ? Dim::kSize + std::size_t{block_length_} * count_ : 0;
  }
  [[nodiscard]] EntryWriter operator[](std::size_t i) const noexcept {
    FASTMM_ASSERT(ok_ && i < count_);
    return EntryWriter(p_ + i * block_length_);
  }

 private:
  std::byte* p_ = nullptr;
  std::size_t count_ = 0;
  std::uint16_t block_length_ = 0;
  bool ok_ = false;
};

}  // namespace fastmm::codecs::sbe
