#pragma once
// Binance USDⓈ-M futures order entry: WebSocket API requests (`order.place`, `order.cancel`,
// `order.modify`) and their REST equivalents (`POST`, `DELETE`, `PUT /fapi/v1/order`), plus the
// signed control-path GETs (open orders, position risk, account settings).
//
// Parameters are added in alphabetical order and signed over the sorted `k=v&...` string
// ("WebSocket API General Info": "Signature payload must be generated by taking all request
// params except for the signature and sorting them by name in alphabetical order"): HMAC-SHA256
// (hex) or Ed25519 (base64). Ed25519 keys log on once per WS API connection (`session.logon`,
// "Only Ed25519 keys are supported for this feature"); after that requests carry neither apiKey
// nor signature, only timestamp/recvWindow. INT parameters are JSON integers and DECIMAL
// parameters JSON strings.
//
//   New      LIMIT with timeInForce GTC | IOC | FOK, post-only as LIMIT + GTX, MARKET without price
//            and timeInForce; reduceOnly=true when the engine set it; positionSide is omitted
//            (BOTH, one-way mode); newOrderRespType=ACK.
//   Cancel   orderId when acknowledged, else origClientOrderId.
//   Replace  order.modify: orderId or origClientOrderId, price, quantity, side. The venue keeps the
//            original clientOrderId and takes the total quantity including what already filled, so
//            quantity = new remaining quantity + executed quantity of the original ("Modify Order":
//            "Both quantity and price must be sent"; the order is cancelled if the new quantity is
//            not above the executed quantity).
//
// Request ids are "<kind><client order id>" (request_id.hpp). No allocation.
#include "fastmm/core/messages.hpp"
#include "fastmm/net/url.hpp"
#include "fastmm/venues/binance/binance_auth.hpp"
#include "fastmm/venues/binance/binance_order_encoder.hpp"
#include "fastmm/venues/order_commands.hpp"
#include "fastmm/venues/request_id.hpp"
#include "fastmm/venues/symbology.hpp"

#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

namespace fastmm::venues::binance_usdm {

using binance::kDefaultRecvWindowMs;
using binance::kMaxRequestBytes;
using binance::RestRequest;
using binance::Signer;

// What the connector remembers about one live order (by the engine's current client id).
struct OrderShadow {
  InstrumentId instrument{};
  Side side = Side::Buy;
  OrderType type = OrderType::Limit;
  TimeInForce tif = TimeInForce::Gtc;
  bool reduce_only = false;
  ClientOrderId link_id{};   // clientOrderId the venue knows the order by (kept by order.modify)
  ClientOrderId replaces{};  // Replace in flight: the engine id being modified
  Qty cum{};                 // venue executedQty seen so far
  Qty base_cum{};            // venue executedQty when this engine id took the order over
};

class BinanceUsdmOrderEncoder {
 public:
  BinanceUsdmOrderEncoder(const Signer& signer,
                          const SymbolTable& symbols,
                          int recv_window_ms = kDefaultRecvWindowMs) noexcept
      : signer_(signer), symbols_(symbols), recv_window_ms_(recv_window_ms) {}

  // Ed25519 sessions: after session.logon apiKey/signature are omitted per request.
  void set_session_authenticated(bool v) noexcept { session_auth_ = v; }
  [[nodiscard]] bool session_authenticated() const noexcept { return session_auth_; }

  // session.logon {apiKey, recvWindow, timestamp, signature}, always signed.
  std::size_t encode_ws_logon(std::string_view request_id,
                              std::int64_t timestamp_ms,
                              std::span<char> out) noexcept;

  // New: `shadow` unused. Cancel: the order's shadow, or nullptr. Replace: the original order's
  // shadow (required). Returns the frame size, 0 if it cannot be encoded.
  std::size_t encode_ws(const OrderCommand& cmd,
                        const OrderShadow* shadow,
                        std::int64_t timestamp_ms,
                        std::span<char> out) noexcept;
  bool encode_rest(const OrderCommand& cmd,
                   const OrderShadow* shadow,
                   std::int64_t timestamp_ms,
                   RestRequest& out) noexcept;

  // DELETE /fapi/v1/allOpenOrders?symbol=S (weight 1).
  bool encode_rest_cancel_all(std::string_view symbol, std::int64_t timestamp_ms, RestRequest& out);
  // GET /fapi/v1/openOrders (weight 1 with a symbol, 40 without).
  bool encode_rest_open_orders(std::string_view symbol,
                               std::int64_t timestamp_ms,
                               RestRequest& out);
  // GET /fapi/v3/positionRisk (weight 5).
  bool encode_rest_position_risk(std::string_view symbol,
                                 std::int64_t timestamp_ms,
                                 RestRequest& out);

  // Any signed GET with an optional symbol, for the control path before attach().
  static bool encode_rest_signed_get(const Signer& signer,
                                     int recv_window_ms,
                                     std::string_view path,
                                     std::string_view symbol,
                                     std::int64_t timestamp_ms,
                                     std::uint32_t weight,
                                     RestRequest& out);

  struct ParamList;

  [[nodiscard]] static std::string_view side_text(Side s) noexcept {
    return s == Side::Buy ? "BUY" : "SELL";
  }
  [[nodiscard]] static std::string_view type_text(OrderType t) noexcept {
    return t == OrderType::Market ? "MARKET" : "LIMIT";
  }
  // Post-only is LIMIT with GTX ("New Order": timeInForce GTX, "Good Till Crossing (Post Only)").
  [[nodiscard]] static std::string_view tif_text(OrderType type, TimeInForce t) noexcept {
    if (type == OrderType::PostOnly) return "GTX";
    switch (t) {
      case TimeInForce::Gtc:
      case TimeInForce::Day:
        return "GTC";
      case TimeInForce::Ioc:
        return "IOC";
      case TimeInForce::Fok:
        return "FOK";
    }
    return "GTC";
  }

 private:
  std::size_t finish_ws(ParamList& params,
                        std::string_view method,
                        std::string_view request_id,
                        std::span<char> out) noexcept;

  const Signer& signer_;
  const SymbolTable& symbols_;
  int recv_window_ms_;
  bool session_auth_ = false;
};

}  // namespace fastmm::venues::binance_usdm
