#!/usr/bin/env python3
"""Writes the Binance Spot SBE market-data fixtures in this directory as commented hex text.

One file = one WebSocket binary frame: the 8-byte SBE header (blockLength, templateId,
schemaId 1, version 0) and the body, packed by hand with struct at the offsets of Binance's
stream_1_0.xml (tools/sbe/binance_spot_stream_1_0.xml), independently of the C++ writers
generated by tools/sbe_gen.py, so the decoder tests cross-check the generated layout. The
values mirror the JSON fixtures one directory up (depth_update.json, book_ticker.json,
trade.json) where a JSON equivalent exists. SBE streams need an Ed25519 API key, so these are
built from the schema, not recorded.

  python3 tests/fixtures/binance/sbe/make_fixtures.py
"""
import pathlib
import struct

HERE = pathlib.Path(__file__).resolve().parent


def frame(template, block_length, body, schema=1, version=0):
    return struct.pack("<HHHH", block_length, template, schema, version) + body


def group32(block_length, entries):
    """groupSizeEncoding: uint16 blockLength, uint32 numInGroup."""
    for e in entries:
        assert len(e) == block_length
    return struct.pack("<HI", block_length, len(entries)) + b"".join(entries)


def group16(block_length, entries):
    """groupSize16Encoding: uint16 blockLength, uint16 numInGroup."""
    for e in entries:
        assert len(e) == block_length
    return struct.pack("<HH", block_length, len(entries)) + b"".join(entries)


def var8(s):
    raw = s.encode()
    return struct.pack("<B", len(raw)) + raw


def levels(pairs):
    return group16(16, [struct.pack("<qq", p, q) for p, q in pairs])


def write(name, comment, data):
    lines = ["# " + line for line in comment.strip().splitlines()]
    lines.append("# generated by make_fixtures.py; %d bytes" % len(data))
    for i in range(0, len(data), 16):
        lines.append(" ".join("%02X" % x for x in data[i:i + 16]))
    (HERE / name).write_text("\n".join(lines) + "\n")


# ---- DepthDiffStreamEvent (10003, blockLength 26) --------------------------------------------
# priceExponent -8, qtyExponent -8: the JSON strings' 8 decimals.
depth = frame(10003, 26,
              struct.pack("<qqqbb", 1789295134334000, 94127, 94129, -8, -8)
              + levels([(7000000000000, 150000000), (6999900000000, 0)])   # bids
              + levels([(7000010000000, 200000000)])                       # asks
              + var8("BTCUSDT"))
write("depth_diff.hex", """
Binance SBE DepthDiffStreamEvent (template 10003, schema 1 v0), btcusdt@depth
eventTime 1789295134334000 us, firstBookUpdateId 94127, lastBookUpdateId 94129
priceExponent -8, qtyExponent -8
  bids: 70000.00000000 x 1.50000000, 69999.00000000 x 0 (delete)
  asks: 70000.10000000 x 2.00000000
symbol BTCUSDT
""", depth)

# ---- BestBidAskStreamEvent (10001, blockLength 50) -------------------------------------------
# Coarser exponents than the JSON (price -2, qty -5) to exercise the scaling.
bbo = frame(10001, 50,
            struct.pack("<qqbbqqqq", 1789295134226000, 94130, -2, -5,
                        7000000, 150000, 7000010, 200000)
            + var8("BTCUSDT"))
write("best_bid_ask.hex", """
Binance SBE BestBidAskStreamEvent (template 10001), btcusdt@bestBidAsk
eventTime 1789295134226000 us, bookUpdateId 94130, priceExponent -2, qtyExponent -5
bid 70000.00 x 1.50000, ask 70000.10 x 2.00000
symbol BTCUSDT
""", bbo)

# ---- TradesStreamEvent (10000, blockLength 18) ------------------------------------------------
# Two trades in one event (the SBE trade stream batches trades of one match).
trades = frame(10000, 18,
               struct.pack("<qqbb", 1789295134226000, 1789295134225000, -8, -8)
               + group32(25, [struct.pack("<qqqB", 388510, 7000010000000, 65000, 1),
                              struct.pack("<qqqB", 388511, 7000020000000, 100000, 0)])
               + var8("BTCUSDT"))
write("trades.hex", """
Binance SBE TradesStreamEvent (template 10000), btcusdt@trade
eventTime 1789295134226000 us, transactTime 1789295134225000 us, exponents -8/-8
  trade 388510: 70000.10000000 x 0.00065000, isBuyerMaker True  (seller aggressed)
  trade 388511: 70000.20000000 x 0.00100000, isBuyerMaker False (buyer aggressed)
  (isBestMatch is a constant, not on the wire)
symbol BTCUSDT
""", trades)

# ---- DepthSnapshotStreamEvent (10002, blockLength 18) -----------------------------------------
snap = frame(10002, 18,
             struct.pack("<qqbb", 1789295134400000, 94131, -8, -8)
             + levels([(7000000000000, 150000000)])
             + levels([(7000010000000, 200000000), (7000020000000, 50000000)])
             + var8("BTCUSDT"))
write("depth_snapshot20.hex", """
Binance SBE DepthSnapshotStreamEvent (template 10002), btcusdt@depth20
eventTime 1789295134400000 us, bookUpdateId 94131, exponents -8/-8
  bids: 70000.00000000 x 1.50000000
  asks: 70000.10000000 x 2.00000000, 70000.20000000 x 0.50000000
symbol BTCUSDT
""", snap)
