#!/usr/bin/env python3
"""Writes the CME MDP 3.0 binary fixtures in this directory as commented hex text.

The bytes are packed by hand with struct at the offsets of CME's templates_FixBinary.xml
(schema id 1, version 13; see tools/sbe/mdp3_templates_subset.xml), independently of the C++
writers generated by tools/sbe_gen.py, so the decoder tests cross-check the generated layout.
sbe_decoding_example_template50.hex is copied verbatim from the CME Client Systems Wiki page
"MDP 3.0 - SBE Decoding Example" and is not produced here.

  python3 tests/fixtures/cme/make_fixtures.py
"""
import pathlib
import struct

HERE = pathlib.Path(__file__).resolve().parent

NULL_I8 = 127
NULL_U8 = 255
NULL_U16 = 65535
NULL_I32 = 2**31 - 1
NULL_U32 = 2**32 - 1
NULL_I64 = 2**63 - 1
NULL_U64 = 2**64 - 1


def message(template, block_length, body, version=13):
    """MsgSize (includes itself) + SBE header (blockLength, templateId, schemaId=1, version)."""
    return struct.pack("<HHHHH", 2 + 8 + len(body), block_length, template, 1, version) + body


def group(block_length, entries):
    """groupSize: uint16 blockLength, uint8 numInGroup."""
    for e in entries:
        assert len(e) == block_length
    return struct.pack("<HB", block_length, len(entries)) + b"".join(entries)


def group8(block_length, entries):
    """groupSize8Byte: uint16 blockLength, uint8 numInGroup at offset 7."""
    for e in entries:
        assert len(e) == block_length
    return struct.pack("<H5xB", block_length, len(entries)) + b"".join(entries)


def block(size, *fields):
    """fields: (offset, struct format, value)."""
    b = bytearray(size)
    for offset, fmt, value in fields:
        struct.pack_into("<" + fmt, b, offset, value)
    return bytes(b)


def chars(s, n):
    raw = s.encode()
    assert len(raw) <= n
    return raw + bytes(n - len(raw))


def packet(seq, sending_time, *messages):
    return struct.pack("<IQ", seq, sending_time) + b"".join(messages)


def write(name, comment, data):
    lines = ["# " + line for line in comment.strip().splitlines()]
    lines.append("# generated by make_fixtures.py; %d bytes" % len(data))
    for i in range(0, len(data), 16):
        lines.append(" ".join("%02X" % x for x in data[i:i + 16]))
    (HERE / name).write_text("\n".join(lines) + "\n")


# ---- MDIncrementalRefreshBook46 (template 46, blockLength 11) --------------------------------
def book_entry(px_mantissa, size, security_id, rpt, orders, level, action, entry_type):
    return block(32,
                 (0, "q", px_mantissa),   # MDEntryPx PRICENULL9
                 (8, "i", size),          # MDEntrySize Int32NULL
                 (12, "i", security_id),  # SecurityID
                 (16, "I", rpt),          # RptSeq
                 (20, "i", orders),       # NumberOfOrders Int32NULL
                 (24, "B", level),        # MDPriceLevel
                 (25, "B", action),       # MDUpdateAction
                 (26, "c", entry_type),   # MDEntryTypeBook
                 (27, "i", NULL_I32))     # TradeableSize Int32NULL (sinceVersion 10)


TT = 1789000000123456789
book = message(46, 11,
               block(11, (0, "Q", TT), (8, "B", 0x84))  # EndOfEvent | LastQuoteMsg
               + group(32, [
                   book_entry(4500250000000, 12, 1234, 1, 3, 1, 0, b"0"),  # New bid 4500.25 x 12
                   book_entry(4500500000000, 7, 1234, 2, 2, 1, 0, b"1"),   # New offer 4500.50 x 7
               ])
               + group8(24, []))
write("book46_two_levels.hex", """
CME MDP 3.0 packet: MsgSeqNum 1001, SendingTime 1789000000123456999
MDIncrementalRefreshBook46 TransactTime 1789000000123456789, MatchEventIndicator 0x84
  entry 1: New Bid   level 1 4500.25 x 12 orders 3 SecurityID 1234 RptSeq 1
  entry 2: New Offer level 1 4500.50 x 7  orders 2 SecurityID 1234 RptSeq 2
  NoOrderIDEntries (groupSize8Byte, blockLength 24) empty
""", packet(1001, 1789000000123456999, book))

# ---- MDIncrementalRefreshTradeSummary48 (template 48, blockLength 11) ----------------------------
trade = message(48, 11,
                block(11, (0, "Q", TT + 1), (8, "B", 0x81))  # EndOfEvent | LastTradeMsg
                + group(32, [block(32,
                                   (0, "q", 4500500000000),  # MDEntryPx PRICE9
                                   (8, "i", 3),              # MDEntrySize
                                   (12, "i", 1234),          # SecurityID
                                   (16, "I", 3),             # RptSeq
                                   (20, "i", 2),             # NumberOfOrders
                                   (24, "B", 1),             # AggressorSide Buy
                                   (25, "B", 0),             # MDUpdateAction New
                                   (26, "I", 777))])         # MDTradeEntryID
                + group8(16, [block(16, (0, "Q", 9001), (8, "i", 2)),
                              block(16, (0, "Q", 9002), (8, "i", 1))]))
write("trade48_buy_aggressor.hex", """
CME MDP 3.0 packet: MsgSeqNum 1002, SendingTime 1789000000123457999
MDIncrementalRefreshTradeSummary48 TransactTime 1789000000123456790, MatchEventIndicator 0x81
  entry: 4500.50 x 3, SecurityID 1234, RptSeq 3, NumberOfOrders 2, AggressorSide 1 (Buy),
         MDUpdateAction New, MDTradeEntryID 777
  NoOrderIDEntries (blockLength 16): OrderID 9001 LastQty 2, OrderID 9002 LastQty 1
""", packet(1002, 1789000000123457999, trade))

# ---- MDInstrumentDefinitionFuture54 (template 54, blockLength 224) --------------------------------
root54 = block(224,
               (0, "B", 0x80),                    # MatchEventIndicator EndOfEvent
               (1, "I", NULL_U32),                # TotNumReports uInt32NULL
               (5, "c", b"A"),                    # SecurityUpdateAction Add
               (6, "Q", 1788900000000000000),     # LastUpdateTime
               (14, "B", 17),                     # MDSecurityTradingStatus ReadyToTrade
               (15, "h", 310),                    # ApplID
               (17, "B", 0),                      # MarketSegmentID
               (18, "B", 5),                      # UnderlyingProduct
               (19, "4s", chars("XCME", 4)),      # SecurityExchange
               (23, "6s", chars("ES", 6)),        # SecurityGroup
               (29, "6s", chars("ES", 6)),        # Asset
               (35, "20s", chars("ESZ6", 20)),    # Symbol
               (55, "i", 1234),                   # SecurityID
               (59, "6s", chars("FUT", 6)),       # SecurityType
               (65, "6s", chars("FFIXSX", 6)),    # CFICode
               (71, "H", 2026),                   # MaturityMonthYear.year
               (73, "B", 12),                     # .month
               (74, "B", NULL_U8),                # .day
               (75, "B", NULL_U8),                # .week
               (76, "3s", chars("USD", 3)),       # Currency
               (79, "3s", chars("USD", 3)),       # SettlCurrency
               (82, "c", b"F"),                   # MatchAlgorithm
               (83, "I", 1),                      # MinTradeVol
               (87, "I", 2000),                   # MaxTradeVol
               (91, "q", 250000000),              # MinPriceIncrement PRICE9 0.25
               (99, "q", 10000000),               # DisplayFactor Decimal9 0.01
               (107, "B", NULL_U8),               # MainFraction
               (108, "B", NULL_U8),               # SubFraction
               (109, "B", 2),                     # PriceDisplayFormat
               (110, "30s", chars("IPNT", 30)),   # UnitOfMeasure
               (140, "q", 50000000000),           # UnitOfMeasureQty Decimal9NULL 50
               (148, "q", NULL_I64),              # TradingReferencePrice PRICENULL9
               (156, "B", 0),                     # SettlPriceType
               (157, "i", NULL_I32),              # OpenInterestQty
               (161, "i", NULL_I32),              # ClearedVolume
               (165, "q", NULL_I64),              # HighLimitPrice
               (173, "q", NULL_I64),              # LowLimitPrice
               (181, "q", NULL_I64),              # MaxPriceVariation
               (189, "i", NULL_I32),              # DecayQuantity
               (193, "H", NULL_U16),              # DecayStartDate
               (195, "i", NULL_I32),              # OriginalContractSize
               (199, "i", NULL_I32),              # ContractMultiplier
               (203, "b", NULL_I8),               # ContractMultiplierUnit
               (204, "b", NULL_I8),               # FlowScheduleType
               (205, "q", 12500000000),           # MinPriceIncrementAmount PRICENULL9 12.5
               (213, "c", b"N"),                  # UserDefinedInstrument
               (214, "H", NULL_U16),              # TradingReferenceDate
               (216, "Q", NULL_U64))              # InstrumentGUID
secdef = message(54, 224,
                 root54
                 + group(9, [block(9, (0, "B", 5), (1, "Q", 1780000000000000000)),     # Activation
                             block(9, (0, "B", 7), (1, "Q", 1797000000000000000))])    # LastEligibleTradeDate
                 + group(4, [block(4, (0, "3s", chars("GBX", 3)), (3, "b", 10)),
                             block(4, (0, "3s", chars("GBI", 3)), (3, "b", 2))])
                 + group(4, [block(4, (0, "I", 0x000A0001))])
                 + group(5, [block(5, (0, "b", 1), (1, "i", 10000))]))  # MinLotSize 1.0000
write("secdef54_esz6.hex", """
CME MDP 3.0 packet: MsgSeqNum 7, SendingTime 1788900000000000999
MDInstrumentDefinitionFuture54: Symbol ESZ6, SecurityID 1234, SecurityGroup ES, Asset ES,
  ApplID 310, MinPriceIncrement 0.25, DisplayFactor 0.01, UnitOfMeasure IPNT,
  UnitOfMeasureQty 50, ContractMultiplier null, maturity 2026-12
  NoEvents: Activation, LastEligibleTradeDate
  NoMDFeedTypes: GBX depth 10, GBI depth 2
  NoInstAttrib: one bitmap; NoLotTypeRules: LotType 1 MinLotSize 1
""", packet(7, 1788900000000000999, secdef))

# ---- mixed administrative packet ---------------------------------------------------------------
heartbeat = message(12, 0, b"")
unknown = message(999, 5, b"\x01\x02\x03\x04\x05")
status = message(30, 30, block(30,
                               (0, "Q", TT + 2),            # TransactTime
                               (8, "6s", chars("ES", 6)),   # SecurityGroup
                               (14, "6s", chars("ES", 6)),  # Asset
                               (20, "i", 1234),             # SecurityID
                               (24, "H", 20710),            # TradeDate
                               (26, "B", 0x80),             # MatchEventIndicator
                               (27, "B", 2),                # SecurityTradingStatus TradingHalt
                               (28, "B", 1),                # HaltReason SurveillanceIntervention
                               (29, "B", 0)))               # SecurityTradingEvent NoEvent
reset = message(4, 9, block(9, (0, "Q", TT + 3), (8, "B", 0x80))
                + group(2, [block(2, (0, "h", 310))]))
write("admin_mixed.hex", """
CME MDP 3.0 packet: MsgSeqNum 1003, SendingTime 1789000000123459999
  AdminHeartbeat12 (blockLength 0)
  template 999 (not in the schema, 5-byte body): must be skipped by MsgSize
  SecurityStatus30: SecurityID 1234, SecurityTradingStatus 2 (TradingHalt), HaltReason 1
  ChannelReset4: ApplID 310
""", packet(1003, 1789000000123459999, heartbeat, unknown, status, reset))
