if(FASTMM_ENABLE_ASAN AND FASTMM_ENABLE_TSAN)
  message(FATAL_ERROR "ASan and TSan are mutually exclusive")
endif()
set(_san "")
if(FASTMM_ENABLE_ASAN)
  list(APPEND _san -fsanitize=address)
endif()
if(FASTMM_ENABLE_UBSAN)
  list(APPEND _san -fsanitize=undefined -fno-sanitize-recover=undefined)
endif()
if(FASTMM_ENABLE_TSAN)
  list(APPEND _san -fsanitize=thread)
endif()
if(_san)
  add_compile_options(${_san} -fno-omit-frame-pointer -O1 -g)
  add_link_options(${_san})
endif()
if(FASTMM_ENABLE_COVERAGE)
  add_compile_options(--coverage -O0 -g)
  add_link_options(--coverage)
endif()
