#pragma once
// Shared helpers for the Nasdaq codec tests: hex fixtures (tests/fixtures/nasdaq, generated by
// generate_fixtures.py from the spec tables), a ring-backed sink that records every event and
// an in-memory byte pipe standing in for a TCP connection.
#include "test_support.hpp"

#include "fastmm/codecs/codec.hpp"
#include "fastmm/core/messages.hpp"
#include "fastmm/core/msg_ring.hpp"
#include "fastmm/venues/event_sink.hpp"

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <map>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace fastmm::codecs::test {

using Bytes = std::vector<std::byte>;

inline Bytes from_hex(std::string_view hex) {
  auto nibble = [](char c) -> unsigned {
    if (c >= '0' && c <= '9') return static_cast<unsigned>(c - '0');
    if (c >= 'a' && c <= 'f') return static_cast<unsigned>(c - 'a' + 10);
    if (c >= 'A' && c <= 'F') return static_cast<unsigned>(c - 'A' + 10);
    FAIL("bad hex digit");
    return 0;
  };
  REQUIRE(hex.size() % 2 == 0);
  Bytes out(hex.size() / 2);
  for (std::size_t i = 0; i < out.size(); ++i)
    out[i] = static_cast<std::byte>((nibble(hex[2 * i]) << 4U) | nibble(hex[2 * i + 1]));
  return out;
}

// name -> bytes of tests/fixtures/nasdaq/<file>.
inline std::map<std::string, Bytes> load_hex_fixture(const std::string& file) {
  const std::string text = fastmm::test::fixture("nasdaq/" + file);
  std::istringstream in(text);
  std::string line;
  std::map<std::string, Bytes> out;
  while (std::getline(in, line)) {
    if (line.empty() || line[0] == '#') continue;
    const std::size_t sp = line.find(' ');
    REQUIRE(sp != std::string::npos);
    out[line.substr(0, sp)] = from_hex(std::string_view(line).substr(sp + 1));
  }
  REQUIRE_FALSE(out.empty());
  return out;
}

inline std::span<const std::byte> span_of(const Bytes& b) {
  return {b.data(), b.size()};
}
inline FrameView frame_of(const Bytes& b) {
  return FrameView{span_of(b), b.size(), 0};
}
inline FrameView frame_of(std::span<const std::byte> b) {
  return FrameView{b, b.size(), 0};
}
inline Bytes to_bytes(std::string_view s) {
  Bytes b(s.size());
  if (!s.empty()) std::memcpy(b.data(), s.data(), s.size());
  return b;
}
inline std::string to_string(std::span<const std::byte> b) {
  return {reinterpret_cast<const char*>(b.data()), b.size()};
}
inline Bytes bytes_of(std::span<const std::byte> s) {
  return {s.begin(), s.end()};
}

// Copies every committed message out of a MsgRing-backed sink.
struct RecordingSink {
  MsgRing ring;
  venues::EventSink sink;
  explicit RecordingSink(std::size_t bytes = 1U << 20)
      : ring(bytes), sink(&ring, venues::SinkPolicy::Drop, 10) {}

  std::vector<Bytes> drain() {
    std::vector<Bytes> out;
    while (const std::byte* p = ring.try_peek()) {
      const auto* h = reinterpret_cast<const EventHeader*>(p);
      out.emplace_back(p, p + h->len);
      ring.release();
    }
    return out;
  }
  template <class M>
  static M as(const Bytes& raw) {
    M m;
    std::memcpy(&m, raw.data(), sizeof(M));
    return m;
  }
  static EventType type_of(const Bytes& raw) {
    return reinterpret_cast<const EventHeader*>(raw.data())->type;
  }
};

// One direction of an in-memory TCP connection.
struct BytePipe {
  Bytes buf;
  std::size_t read = 0;
  bool fail = false;
  bool send(std::span<const std::byte> b) noexcept {
    if (fail) return false;
    buf.insert(buf.end(), b.begin(), b.end());
    return true;
  }
  [[nodiscard]] std::span<const std::byte> pending() const {
    return {buf.data() + read, buf.size() - read};
  }
  void consume(std::size_t n) {
    read += n;
    if (read == buf.size()) {
      buf.clear();
      read = 0;
    }
  }
  void drop_all() {
    buf.clear();
    read = 0;
  }
};

}  // namespace fastmm::codecs::test
