file(GLOB_RECURSE FASTMM_VENUES_SOURCES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
file(GLOB_RECURSE FASTMM_VENUES_HEADERS CONFIGURE_DEPENDS ${PROJECT_SOURCE_DIR}/include/fastmm/venues/*.hpp)
add_library(fastmm_venues STATIC ${FASTMM_VENUES_SOURCES} ${FASTMM_VENUES_HEADERS})
add_library(fastmm::venues ALIAS fastmm_venues)
set_target_properties(fastmm_venues PROPERTIES EXPORT_NAME venues)
fastmm_target_defaults(fastmm_venues)
target_link_libraries(fastmm_venues PUBLIC fastmm::net fastmm::codecs PRIVATE simdjson::simdjson)
